spring.application.name=crudByJpa


spring.datasource.url=jdbc:postgresql://localhost:5432/secondDB
spring.datasource.username=postgres
spring.datasource.password=root1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect